export {
  COGNITION_AUDIT_STORAGE_PLAN,
  FileCognitionAuditSink,
  InMemoryCognitionAuditSink,
  cognitionAuditEventRef,
  createCognitionReplayRecord,
} from "./audit-sink.js";
export {
  CloudBoundaryEvaluationSchema,
  CloudBoundaryCallerPathSchema,
  CloudBoundaryModeSchema,
  CloudRefClassificationSchema,
  CloudRefClassSchema,
  classifyCognitionMemorySourceForCloud,
  evaluateCloudBoundaryForCognition,
} from "./cloud-boundary.js";
export {
  CompanionCognitionKernel,
  CompanionCognitionService,
} from "./companion-cognition-service.js";
export {
  AuthorizationRequestSchema,
  AuthorityHandoffSchema,
  CandidateActionSchema,
  ChatSessionCognitionContextSchema,
  CloudAdmittedRefVersionSchema,
  CloudComputeRequestSchema,
  CloudComputePurposeSchema,
  CloudRetentionExpectationSchema,
  CognitionEventRefSchema,
  CognitionCorrelationRefsSchema,
  CognitionMemoryRequestSchema,
  CognitionMemoryResultSchema,
  CognitionMemorySourceSchema,
  CognitionRedactionPolicySchema,
  CognitionRefSchema,
  CognitionReplayRecordSchema,
  CognitionSourceStoreSchema,
  CognitionUncertaintySchema,
  CognitionWritebackReflectionInputSchema,
  CommitmentAttentionHandoffSchema,
  CompanionCognitionCallerPathSchema,
  CompanionCognitionInputSchema,
  CompanionCognitionOutputSchema,
  CompanionCognitionSurfaceTargetSchema,
  ExternalDataScopeGrantSchema,
  ExternalDataScopeUseSchema,
  GoalIntentionContextSchema,
  GoalRefSchema,
  IntentionLifecycleSchema,
  IntentionSelectionSchema,
  MemoryWritebackProposalSchema,
  MemoryUseAuditSchema,
  ModelContextPolicySchema,
  PrivacyProfileSchema,
  ProactiveDeliveryKindSchema,
  ReflectionHintSchema,
  RelationshipProjectionSourceRefSchema,
  RelationshipProjectionTurnRefSchema,
  RelationshipStateProjectionV2Schema,
  RelationshipSurfaceAllowedUseSchema,
  RelationshipSurfaceFactRoleSchema,
  RelationshipSurfaceFactSchema,
  RelationshipSurfaceRepairPathSchema,
  RelationshipStateProjectionSchema,
  RelationshipWithheldFactSchema,
  ResponsePlanSchema,
  RuntimeCognitionContextSchema,
  SideEffectProfileSchema,
  SituationModelSchema,
  ToolAuthorityStageSchema,
  ToolCandidateSchema,
  ToolRiskClassSchema,
  WorkingContextSnapshotSchema,
  deliveryKindRank,
} from "./contracts.js";
export {
  createEmptyCognitionMemoryResult,
  createRelationshipProfileCognitionMemoryPort,
  cognitionMemoryResultFromCoreProjection,
} from "./memory-context.js";
export {
  renderCompanionCognitionGatewaySystemPrompt,
} from "./model-context-policy-projection.js";
export {
  createRelationshipStateProjectionV2,
  relationshipCharacterPolicyProjectionRef,
  relationshipTurnRefForCognitionInput,
} from "./relationship-state-projection.js";
export {
  RelationshipMemoryNormalSummarySchema,
  projectRelationshipMemoryNormalSummary,
} from "./relationship-normal-summary.js";
export {
  MEMORY_LIFECYCLE_OWNER_ROUTING_TABLE,
  MemoryLifecycleCanonicalOwnerSchema,
  MemoryLifecycleOwnerRoutingRuleSchema,
  MemoryLifecycleProposedTargetSchema,
  MemoryLifecycleWritebackOwnerSchema,
  ownerForMemoryWritebackProposal,
  ownerRoutingRuleForProposal,
} from "./memory-writeback-owner-routing.js";
export {
  assembleSituationModel,
} from "./situation.js";
export {
  createCloudComputeAuthorizationRequest,
  toolCandidateFromGadgetPlan,
} from "./tool-authority.js";
export {
  createReflectionHintForWriteback,
  createReflectionInputFromCognitionReplay,
  createTurnEpisodeWritebackProposal,
} from "./writeback.js";
export type {
  CognitionAuditSink,
  CognitionMemoryPort,
  CognitionWritebackPort,
} from "./ports.js";
export type {
  CloudBoundaryEvaluation,
  CloudBoundaryCallerPath,
  CloudRefClassification,
  CloudRefClass,
  CloudBoundaryMode,
} from "./cloud-boundary.js";
export type {
  AuthorizationRequest,
  AuthorityHandoff,
  CandidateAction,
  ChatSessionCognitionContext,
  CloudAdmittedRefVersion,
  CloudComputeRequest,
  CloudComputePurpose,
  CloudRetentionExpectation,
  CognitionEventRef,
  CognitionCorrelationRefs,
  CognitionMemoryRequest,
  CognitionMemoryResult,
  CognitionMemorySource,
  CognitionRedactionPolicy,
  CognitionRef,
  CognitionReplayRecord,
  CognitionRequestedMemoryUse,
  CognitionSourceStore,
  CognitionUncertainty,
  CognitionWritebackReflectionInput,
  CommitmentAttentionHandoff,
  CompanionCognitionCallerPath,
  CompanionCognitionInput,
  CompanionCognitionOutput,
  CompanionCognitionSurfaceTarget,
  ExternalDataScopeGrant,
  ExternalDataScopeUse,
  GoalIntentionContext,
  GoalRef,
  IntentionLifecycle,
  IntentionSelection,
  MemoryWritebackProposal,
  MemoryUseAudit,
  ModelContextPolicy,
  PrivacyProfile,
  ProactiveDeliveryKind,
  ReflectionHint,
  RelationshipProjectionSourceRef,
  RelationshipProjectionTurnRef,
  RelationshipStateProjectionV2,
  RelationshipSurfaceAllowedUse,
  RelationshipSurfaceFact,
  RelationshipSurfaceFactRole,
  RelationshipSurfaceRepairPath,
  RelationshipStateProjection,
  RelationshipWithheldFact,
  ResponsePlan,
  RuntimeCognitionContext,
  SideEffectProfile,
  SituationModel,
  ToolAuthorityStage,
  ToolCandidate,
  ToolRiskClass,
  WorkingContextSnapshot,
} from "./contracts.js";
export type {
  CompanionCognitionKernelDeps,
  CompanionCognitionServiceDeps,
} from "./companion-cognition-service.js";
export type {
  RelationshipMemoryNormalSummary,
} from "./relationship-normal-summary.js";
export type {
  MemoryLifecycleCanonicalOwner,
  MemoryLifecycleOwnerRoutingRule,
  MemoryLifecycleProposedTarget,
  MemoryLifecycleWritebackOwner,
} from "./memory-writeback-owner-routing.js";
